### ISSUE TITLE
ImportError: cannot import name config

### ISSUE THREAD

**Issue by dongchen1999** [zonyl/pytomation#29]
>>> import pytomation.interfaces
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pytomation/interfaces/__init__.py", line 1, in <module>
    from .common import *
  File "pytomation/interfaces/common.py", line 42, in <module>
    from pytomation.common.pytomation_object import PytomationObject
  File "pytomation/common/__init__.py", line 1, in <module>
    from .pytomation_system import *
  File "pytomation/common/pytomation_system.py", line 3, in <module>
    from .pytomation_object import PytomationObject
  File "pytomation/common/pytomation_object.py", line 1, in <module>
    from .pyto_logging import PytoLogging
  File "pytomation/common/pyto_logging.py", line 4, in <module>
    from ..common import config
ImportError: cannot import name config

I tried but still can not solve it. Please give me some help.

**Comment by king-dopey** [comment]
You have to copy pytomation/common/config_example.py to pytomation/common/config.py and edit the configuraiton option to suit your needs. This is noted in the "Configuring" section of the documentation, but it probably needs to go in the "Installing" section too.

**Comment by texnofobix** [comment]
Did that work Dongchen1999? If so I will close this issue.

**Comment by texnofobix** [comment]
Maybe this should respond with a more friendly message of a recommended resolution?

**Comment by dongchen1999** [comment]
Yes. Thanks.

**Comment by dongchen1999** [comment]
One more question. For INSTEON Stuff, before using Pytomation to manage them, I should pair them first manually by clicking the setting button. The pytomation does not support auto-pair without manually clicking button. Right?

**Comment by texnofobix** [comment]
I'm not familiar with the Insteon devices. Hopefully someone will give you a good answer there.

**Comment by dongchen1999** [comment]
Ok. Thanks
Dong

**Comment by texnofobix** [comment]
Fixed with https://github.com/zonyl/pytomation/commit/e255fffb6e00b401fb17e9920b0ad6b4ec3d528b
